-- PHASE 1: SNOWFLAKE ENVIRONMENT
-- Create Warehouse
CREATE WAREHOUSE RETAIL_WH
WITH WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

-- Use Warehouse
USE WAREHOUSE RETAIL_WH;

-- Create Database
CREATE DATABASE RETAIL_DB;

-- Create Schema
CREATE SCHEMA RETAIL_DB.SALES_SCHEMA;

-- Use Database and Schema
USE DATABASE RETAIL_DB;
USE SCHEMA SALES_SCHEMA;

-- CREATE CSV FILE FORMAT
CREATE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- CREATE INTERNAL STAGE
CREATE STAGE SALES
FILE_FORMAT=CSV_FORMAT;

-- Check stage
SHOW STAGES;

-- PHASE 2: CREATE TABLES
-- Customer table
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(50),
    CITY VARCHAR(100),
    MEMBERSHIP VARCHAR(20)
);

-- Products table
CREATE TABLE PRODUCTS
(
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2)
);

-- Branches table
CREATE TABLE BRANCHES
(
    BRANCH_ID INT,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100)
);

-- Sales table
CREATE TABLE SALES
(
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);


-- ============================================================
-- UPLOAD FILES TO INTERNAL STAGE
-- ============================================================

-- Upload these files through Snowflake UI / PUT command:
-- customers.csv
-- products.csv
-- branches.csv
-- sales.csv

-- Example using PUT if files are accessible from SnowSQL:
-- PUT 'file://C:/path/customers.csv' @SALES;
-- PUT 'file://C:/path/products.csv' @SALES;
-- PUT 'file://C:/path/branches.csv' @SALES;
-- PUT 'file://C:/path/sales.csv' @SALES;

-- Check files in stage
LIST @SALES;

-- LOAD DATA USING COPY INTO
COPY INTO CUSTOMER
FROM @SALES/customers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO PRODUCTS
FROM @SALES/products.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO BRANCHES
FROM @SALES/branches.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO SALES
FROM @SALES/sales.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- VERIFY IMPORTED RECORDS
SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCTS;
SELECT * FROM BRANCHES;
SELECT * FROM SALES;

-- PHASE 3: SQL ANALYTICS
-- 1. Display all customers
SELECT * FROM CUSTOMER;

-- 2. Display all products
SELECT * FROM PRODUCTS;

-- 3. Display all branches
SELECT * FROM BRANCHES;

-- 4. Display all sales transactions
SELECT * FROM SALES;

-- 5. Total business revenue
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_BUSINESS_REVENUE FROM SALES;

-- 6. Customer-wise sales
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID=S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC;

-- 7. Branch-wise sales
SELECT B.BRANCH_ID,B.BRANCH_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM BRANCHES B JOIN SALES S
ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY B.BRANCH_ID,B.BRANCH_NAME
ORDER BY TOTAL_SALES DESC;

-- 8. Product-wise sales
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM PRODUCTS P JOIN SALES S
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

-- 9. Category-wise sales
SELECT P.CATEGORY,SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM PRODUCTS P JOIN SALES S
ON P.PRODUCT_ID=S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_SALES DESC;

-- 10. Highest revenue branch
SELECT B.BRANCH_ID,B.BRANCH_NAME,
SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B JOIN SALES S
ON B.BRANCH_ID=S.BRANCH_ID
GROUP BY B.BRANCH_ID,B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- 11. Highest spending customer
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID=S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;

-- 12. Top three products by revenue
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P JOIN SALES S
ON P.PRODUCT_ID=S.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

-- 13. Top three customers by spending
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID=S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

-- PHASE 4: WINDOW FUNCTIONS
-- 1. Rank customers based on total spending
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING,RANK() OVER (
ORDER BY SUM(S.TOTAL_AMOUNT) DESC
) AS CUSTOMER_RANK
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID=S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

-- 2. Rank branches based on total sales
SELECT B.BRANCH_ID,B.BRANCH_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,RANK() OVER (
ORDER BY SUM(S.TOTAL_AMOUNT) DESC
) AS BRANCH_RANK
FROM BRANCHES B JOIN SALES S
ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY B.BRANCH_ID,B.BRANCH_NAME
ORDER BY BRANCH_RANK;

-- 3. Top-selling product in each category
--    using ROW_NUMBER()
WITH PRODUCT_REVENUE AS(
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P JOIN SALES S
ON P.PRODUCT_ID=S.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY
),
RANKED_PRODUCTS AS (
SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,TOTAL_REVENUE,
ROW_NUMBER() OVER (
PARTITION BY CATEGORY
ORDER BY TOTAL_REVENUE DESC
) AS ROW_NUM
FROM PRODUCT_REVENUE
)
SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,TOTAL_REVENUE
FROM RANKED_PRODUCTS
WHERE ROW_NUM = 1
ORDER BY CATEGORY;

-- 4. Cumulative sales using SUM() OVER()
SELECT SALE_DATE,SUM(TOTAL_AMOUNT) AS DAILY_SALES,
SUM(SUM(TOTAL_AMOUNT)) OVER (
ORDER BY SALE_DATE
) AS CUMULATIVE_SALES
FROM SALES
GROUP BY SALE_DATE
ORDER BY SALE_DATE;

-- 5. Average sale amount using AVG() OVER()
SELECT SALE_ID,SALE_DATE,TOTAL_AMOUNT,AVG(TOTAL_AMOUNT) OVER (
ORDER BY SALE_DATE
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
) AS RUNNING_AVERAGE_SALES
FROM SALES
ORDER BY SALE_DATE;

-- PHASE 5: COMMON TABLE EXPRESSIONS (CTE)
-- 1. Customer-wise revenue using CTE
WITH CUSTOMER_REVENUE AS
(
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
)
SELECT * FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

-- 2. Customers spending greater than average spending
WITH CUSTOMER_REVENUE AS
(SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID=S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
),
AVERAGE_SPENDING AS
(SELECT AVG(TOTAL_SPENDING) AS AVG_CUSTOMER_SPENDING
FROM CUSTOMER_REVENUE
)
SELECT CR.CUSTOMER_ID,CR.CUSTOMER_NAME,CR.TOTAL_SPENDING
FROM CUSTOMER_REVENUE CR
CROSS JOIN AVERAGE_SPENDING A
WHERE CR.TOTAL_SPENDING > A.AVG_CUSTOMER_SPENDING
ORDER BY CR.TOTAL_SPENDING DESC;

-- PHASE 6: VIEWS
-- 1. Create SALES_REPORT view
CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,C.MEMBERSHIP,
SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,C.MEMBERSHIP;

-- Query SALES_REPORT
SELECT * FROM SALES_REPORT
ORDER BY TOTAL_SALES DESC;

-- 2. Create TOP_CUSTOMERS materialized view
CREATE OR REPLACE VIEW TOP_CUSTOMERS AS
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER C JOIN SALES S
ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME;

-- Query TOP_CUSTOMERS
SELECT * FROM TOP_CUSTOMERS
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;